apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-caddy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/michaelochristensen/cloudflared-caddy-k8s.git
    targetRevision: main
    path: charts/cloudflared-caddy
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
