apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.caddy.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared-caddy.labels" . | nindent 4 }}
data:
  Caddyfile: |
{{ .Values.caddy.caddyfile | nindent 4 }}
