{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudflared.tokenSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared-caddy.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.cloudflared.token | quote }}
{{- end }}
