{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.caddy.teslaKeySecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared-caddy.labels" . | nindent 4 }}
type: Opaque
stringData:
  com.tesla.3p.public-key.pem: |
{{ .Values.caddy.teslaPublicKey | nindent 4 }}
{{- end }}
